config/routes.rb
Proj2::Application.routes.draw do

  get "guest_user/show"
  resources :users do
    member do
      get 'random_recipe'
    end
    resources :recipes do
      resources :ingredients 
    end
  end

  root 'guest_user#show'

  

end

app/models/front.rb
class Front < ActiveRecord::Base

  has_one :user

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  has_many :ingredients
  belongs_to :user
  accepts_nested_attributes_for :ingredients, allow_destroy: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :recipes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fronts_controller.rb
class FrontsController < ApplicationController
  before_action :set_front, only: [:show, :edit, :update, :destroy]

  # GET /fronts
  # GET /fronts.json
  def index
    @fronts = Front.all
    @users = User.all
  end

  # GET /fronts/1
  # GET /fronts/1.json
  def show
  end

  # GET /fronts/new
  def new
    @front = Front.new
  end

  # GET /fronts/1/edit
  def edit
  end

  # POST /fronts
  # POST /fronts.json
  def create
    @front = Front.new(front_params)

    respond_to do |format|
      if @front.save
        format.html { redirect_to @front, notice: 'Front was successfully created.' }
        format.json { render action: 'show', status: :created, location: @front }
      else
        format.html { render action: 'new' }
        format.json { render json: @front.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fronts/1
  # PATCH/PUT /fronts/1.json
  def update
    respond_to do |format|
      if @front.update(front_params)
        format.html { redirect_to @front, notice: 'Front was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @front.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fronts/1
  # DELETE /fronts/1.json
  def destroy
    @front.destroy
    respond_to do |format|
      format.html { redirect_to fronts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_front
      @front = Front.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def front_params
      params[:front]
    end
end

app/controllers/guest_user_controller.rb
class GuestUserController < ApplicationController
  before_action :set_guest_user, only:[:show]

  def show
    recipes = @Guest_user.recipes
    @random_recipe = recipes[rand(recipes.length)]
  end


  private
    def set_guest_user
      @Guest_user = User.find(1)
    end
  

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

def create
  puts 'here!!!!'
  @user = User.find(params[:user_id])
  @recipe = Recipe.find(params[:recipe_id])
  @ingredient = @recipe.ingredients.create(ingredient_params)
  # flash[:notice] = "Ingredient has been created!"
  @recipe.ingredients << @ingredient
  redirect_to edit_user_recipe_path(@user,@recipe)
end

def edit
end

# def update
#   @recipe = recipe.find(params[:recipe_id])
#   if @recipe.ingredients.update(recipe_params)
#     @ingredient = @recipe.ingredients.update(ingredient_params)
#     flash[:notice] = "Ingredient successfully updated!"
#     redirect_to recipe_path(@recipe)
#   else
#     render.html {render action: 'edit' }
#   end
# end
#
# def destroy
#   @recipe = Recipe.find(params[:recipe_id])
#   @ingredient = @recipe.ingredients.destroy
#   redirect_to recipe_path(@recipe)
# end


private
  def ingredient_params
    params.require(:ingredient).permit(:name)
end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = User.find(1).recipes
  end

def create
  @user = User.find(1)
  flash[:notice] = "Recipe has been created!"
  redirect_to user_path(@user)
end

def show
end

def new
  @user = User.find(1)
  @recipe = @user.recipes.create
end

def edit
  @user = User.find(1)
end

def update
  @user = User.find(1)
  if @recipe.update(recipe_params)
    redirect_to user_recipe_path(@user, @recipe )
  end
end

def destroy
  @user = User.find(params[:user_id])
  @recipe = @user.recipes.destroy
  redirect_to user_path(@user)
end


private
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
 

  def recipe_params
    params.require(:recipe).permit(:name, :ingredients_attributes => [:id, :name, :_destroy])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fronts_helper.rb
module FrontsHelper
end

app/helpers/guest_user_helper.rb
module GuestUserHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fronts/_form.html.erb
<%= form_for(@front) do |f| %>
  <% if @front.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@front.errors.count, "error") %> prohibited this front from being saved:</h2>

      <ul>
      <% @front.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fronts/edit.html.erb
<h1>Editing front</h1>

<%= render 'form' %>

<%= link_to 'Show', @front %> |
<%= link_to 'Back', fronts_path %>

app/views/fronts/index.html.erb
<p id="notice"><%= notice %></p>
<div>

  <%= @front.methods %><br><br>
  <%= @fronts.methods %><br><br>
  <%= @fronts.many? %><br><br>
  <%= @fronts.any? %><br><br>
  
  <%= @user.methods %><br><br>
  <%= @users.methods %><br><br>
  <%= @users.instance_variables %>
<br>
  <%= @user.to_enum %>
<br>
<br>
  <%= @user.to_a.length %>
<br>
<br>
  <%= @user.to_a.methods %>
<br>
<br>
  <%= @user.to_a.size%>
<br>
<br>
  <%= @user.to_a.all? %>
<br>
<br>
  <%= @user.to_a.find_all %>
</div>
<br><br>
<div>

  <%-# render @users.list -%> 
  <%-# commented line -%>
  <%-# render @users.recipes %>
  <%-# render "recipes/form" %> 

</div>

app/views/fronts/new.html.erb
<h1>New front</h1>

<%= render 'form' %>

<%= link_to 'Back', fronts_path %>

app/views/fronts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_front_path(@front) %> |
<%= link_to 'Back', fronts_path %>

app/views/guest_user/show.html.erb
<div><br>
<%= @random_recipe.name %><br><br>
<ul class="IngredientList">
<% @random_recipe.ingredients.each do |i| %>
  <li><%= i.name %><br></li>
<% end %>
</ul>
</div>
<br><br>

<div>
  <%= link_to 'Different Recipe', request.url, class: 'refresh-recipe-button' %> &nbsp;&nbsp;&nbsp; 
  <%= link_to 'New Recipe', new_user_recipe_path(1), class: 'refresh-recipe-button' %> &nbsp;&nbsp;&nbsp; 
  <%= link_to 'All Recipes',  user_recipes_path(1), class: 'refresh-recipe-button' %> &nbsp;&nbsp;&nbsp; 
</div>

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :img_path %><br>
    <%= f.text_field :img_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Img path</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.img_path %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Img path:</strong>
  <%= @ingredient.img_path %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>What's For Dinner?</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<p><id = "Logo"> <%= link_to(image_tag("Logo1.png", :alt => "rss feed"), "/") %> </p>

<body>
<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for([@user, @recipe]) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
 
  </div><br>
  Ingredients: <br>
<!--  <% @recipe.ingredients.each_with_index do |i,j| %>
    <div class="field">
      <%= label_tag 'ingredient_name_'+j.to_s, '' %>
      <%= text_field_tag 'ingredient_name_'+j.to_s, i.name %>
    </div>
  <% end %> -->

  <%= f.fields_for :ingredients do |i_fields| %>
		<div class="field">
	    <%= i_fields.hidden_field :id %>
		</div>
    <div class="field" >
	    <%= i_fields.text_field  :name  %>
		  <%= i_fields.check_box :_destroy %>
		  <%= i_fields.label :_destroy, "Remove Ingredient" %>
    </div>										
  <% end %>

										
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
													
<br />													
<%= form_for([@user, @recipe, @recipe.ingredients.new]) do |ni_f| %>
  <div class="field">
    <%= ni_f.label :name, 'New Ingredient: ' %> 
    <%= ni_f.text_field :name %>
    <%= ni_f.submit %>
  </div>
<% end %>
<br />	

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', user_recipe_path( @user, @recipe)  %> 

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.name, user_recipe_path(recipe.user, recipe) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_user_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', user_recipes_path %>


~                    

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>

<ul class="IngredientList">
<% @recipe.ingredients.each do |i| %>
  <li><%= i.name %><br></li>
<% end %>
</ul>


</p>

<%= link_to 'Edit', edit_user_recipe_path(@recipe.user, @recipe) %> |
<%= link_to 'Back', user_recipes_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>